---

- name: Playbook to configure My Desktop
  hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml

  roles:
    - { role: desktop, tags: ['desktop'] }
    - { role: chrome,  tags: ['chrome']  }
    - { role: atom,    tags: ['atom']    }
    - { role: docker,  tags: ['docker']  }
    - { role: vagrant, tags: ['vagrant'] }
